id: ro-crate-metadata-schema
name: ROCrateMetadataSchema
description: A schema to validate the RO-Crate metadata entity.
prefixes:
  linkml: https://w3id.org/linkml/
  ro: https://w3id.org/ro/crate/1.1/context/

default_prefix: ro
default_range: string

classes:
  ROCrateMetadata:
    description: A class representing the RO-Crate metadata.
    slots:
      - id
      - type
      - about
      - conforms_to
    tree_root: true

  About:
    description: A class representing the 'about' field.
    slots:
      - id

  ConformsTo:
    description: A class representing the 'conformsTo' field.
    slots:
      - id

slots:
  id:
    name: id
    alias: "@id"
    identifier: true
    range: string
    required: true

  type:
    name: type
    alias: "@type"
    range: uriorcurie
    required: true

  about:
    name: about
    alias: "https://w3id.org/ro/crate/1.1/context/about"
    range: About
    required: true

  conforms_to:
    name: conforms_to
    alias: "https://w3id.org/ro/crate/1.1/context/conformsTo"
    range: ConformsTo
    required: true
